---
  - hosts: all
    name: Add cis-92 packages
    become: yes
    tasks:
      - name: Install packages 
        ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 3600
          name:
            - apache2
            - php
            - php-xml

      - name: Mount second persistent disk
        ansible.posix.mount:
          path: /var/www
          src: /dev/disk/by-id/google-doukwiki_disk
          fstype: ext4
          state: present

      - name: Create directory
        ansible.builtin.file:
          path: /var/www
          state: directory

      - name: Extract https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz into /var/www/html
        ansible.builtin.unarchive:
          src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
          dest: /var/www/html
          remote_src: yes

      - name: Change file ownership
        ansible.builtin.file:
          path: /var/www/html/dokuwiki
          state: directory
          recurse: yes
          owner: www-data
          group: www-data

      - name: Files older than six months should be deleted automatically
        ansible.builtin.copy:
          src: backup
          dest: /etc/cron.hourly
          owner: root
          group: root
          mode: '0744'

  